### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by mackenza** [sitespeedio/run.sitespeed.io#3]
http://condorshockey.org

**Comment by soulgalore** [comment]
HI @mackenza 
thanks for reporting! That's strange, I didn't get an automated error report for the URL, need to look into that. Tested and it worked for me:
https://results.sitespeed.io/f79f-2015/6/18/daa3b7d3-9919-4e3b-afec-66f3b75d2194/index.html

Best
Peter

**Comment by mackenza** [comment]
I did it from my android phone... not sure if that was the issue or not... it seems to work now on my windows box
